#conding: utf-8


CoIndependentTrait.create(:contents=>"自らを犠牲にして、相手を助けたり世話をしたりする") unless CoIndependentTrait.exists?(:id =>1)
CoIndependentTrait.create(:contents=>"相手の行動・感情・考え方・状態・結果を変えようとコントロールする")  unless CoIndependentTrait.exists?(:id =>2)
CoIndependentTrait.create(:contents=>"問題や危機が起こっているような人間関係に巻き込まれることが多い") unless CoIndependentTrait.exists?(:id =>3)
CoIndependentTrait.create(:contents=>"依存心が強く、一人でやっていけるという自信がない") unless CoIndependentTrait.exists?(:id =>4)
CoIndependentTrait.create(:contents=>"ある特定のことで頭がいっぱいで、他のことを考えられない") unless CoIndependentTrait.exists?(:id =>5)
CoIndependentTrait.create(:contents=>"自分の問題は大したことはないと思ったり、いやなことを見て見ぬふりをしたり、表面上は何でもないようにふるまう") unless CoIndependentTrait.exists?(:id =>6)
CoIndependentTrait.create(:contents=>"相手との境界線がはっきりせず、相手が落ち込んでいると自分も落ち込んでしまったりする") unless CoIndependentTrait.exists?(:id =>7)
CoIndependentTrait.create(:contents=>"他人の問題にのめりこんだり、相手からの精神的・身体的・性的侵入を許してしまう") unless CoIndependentTrait.exists?(:id =>8)
CoIndependentTrait.create(:contents=>"罪の意識におそわれやすく、相手の問題は自分のせいだと思い込んでしまいやすい") unless CoIndependentTrait.exists?(:id =>9)
CoIndependentTrait.create(:contents=>"過去の人間関係の間違いから学ぶことができず、同じ間違いを繰り返す傾向がある") unless CoIndependentTrait.exists?(:id =>10)
CoIndependentTrait.create(:contents=>"被害者意識にとらわれて、自分は犠牲者だと思い込み弱弱しくなる") unless CoIndependentTrait.exists?(:id =>11)
CoIndependentTrait.create(:contents=>"自分の周りに害があるのに、波風を立てないように問題を明らかにしない") unless CoIndependentTrait.exists?(:id =>12)
CoIndependentTrait.create(:contents=>"相手から離れられずにしがみついていることを愛情と取り違えている") unless CoIndependentTrait.exists?(:id =>13)
CoIndependentTrait.create(:contents=>"「こうあるべきだ」という社会通念、「こうなるはずだ」というファンタジーにとらわれやすい") unless CoIndependentTrait.exists?(:id =>14)
CoIndependentTrait.create(:contents=>"相手の気持ちを敏感に察して、先へ先へと頭を働かせたり気を配ったりする") unless CoIndependentTrait.exists?(:id =>15)
CoIndependentTrait.create(:contents=>"「ノー」と言えず、何でもかんでも引き受けて、疲れてしまったり恨みが積もったりする") unless CoIndependentTrait.exists?(:id =>16)
CoIndependentTrait.create(:contents=>"責任感が強すぎて、何でもがむしゃらにやりこなす") unless CoIndependentTrait.exists?(:id =>17)
