#認知
CognitiveDistortion.create({:name=>"根拠のない決めつけ", :discription=>"証拠がないままに、思いつきを信じ込むこと"})
CognitiveDistortion.create({:name=>"白黒思考", :discription=>"灰色（曖昧な状態）に耐えられず、物事を白か黒か、極端な考え方で割り切ろうとする考え方"})
CognitiveDistortion.create({:name=>"部分的焦点づけ", :discription=>"自分が着目していることだけに目をむけ、短絡的に結論づけること"})
CognitiveDistortion.create({:name=>"過大評価・過少評価", :discription=>"自分が関心のあることは拡大して捉え、反対に自分の考えや予想に合わない部分はことさら小さく見ること"})
CognitiveDistortion.create({:name=>"べき思考", :discription=>"「こうすべきだ」「あのようにすべきでなかった」と過去のことをあれこれ思い出して悔やんだり、自分の行動を自分で制限して自分を責めること。また、それを他人に押し付けること"})
CognitiveDistortion.create({:name=>"極端な一般化", :discription=>"少数の事実を取り上げ、すべてのことが同様の結果になるだろうと結論づけてしまうこと"})
CognitiveDistortion.create({:name=>"自己関連付け", :discription=>"何か悪いことが起きると、自分のせいで起こったのだと自分を責めてしまうこと"})
CognitiveDistortion.create({:name=>"情緒的な理由付け", :discription=>"そのときの感情に基づいて、現実を判断してしまう。"})
CognitiveDistortion.create({:name=>"自分で実現してしまう予言", :discription=>"自分で否定的予測を立てて、自分の行動を制限してしまう。その結果失敗し、否定的な予測をますます信じ込み悪循環に陥ること。"})
